import type { Metadata } from "next";
import {
  Space_Grotesk,
  Nunito,
  Merriweather,
  Lobster,
  Orbitron,
  Felipa,
} from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/global.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/lib/ThemeContext";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-space-grotesk",
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-nunito",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-merriweather",
});

const lobster = Lobster({
  subsets: ["latin"],
  weight: ["400"], // only 400 available
  variable: "--font-lobster",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
  variable: "--font-orbitron",
});

const felipa = Felipa({
  subsets: ["latin"],
  weight: ["400"], // only 400 available
  variable: "--font-felipa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${spaceGrotesk.variable}
          ${nunito.variable}
          ${merriweather.variable}
          ${lobster.variable}
          ${orbitron.variable}
          ${felipa.variable}
        `}
      >
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
